// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_make_300_limitless_score_in_one_go = "CgkIpb2krYUDEAIQGg"; // <GPGSID>
        public const string achievement_complete_all_60_classic_levels = "CgkIpb2krYUDEAIQBg"; // <GPGSID>
        public const string achievement_make_200_limitless_score_in_one_go = "CgkIpb2krYUDEAIQFg"; // <GPGSID>
        public const string achievement_make_400_limitless_score_in_one_go = "CgkIpb2krYUDEAIQGw"; // <GPGSID>
        public const string achievement_unlock_limitless_category = "CgkIpb2krYUDEAIQAw"; // <GPGSID>
        public const string achievement_complete_40_classic_levels = "CgkIpb2krYUDEAIQCA"; // <GPGSID>
        public const string achievement_make_250_limitless_score_in_one_go = "CgkIpb2krYUDEAIQGQ"; // <GPGSID>
        public const string achievement_collect_10_limitless_diamonds_in_one_go = "CgkIpb2krYUDEAIQDQ"; // <GPGSID>
        public const string achievement_collect_200_limitless_diamonds_in_one_go = "CgkIpb2krYUDEAIQGA"; // <GPGSID>
        public const string achievement_collect_40_limitless_diamonds_in_one_go = "CgkIpb2krYUDEAIQDw"; // <GPGSID>
        public const string achievement_collect_100_limitless_diamonds_in_one_go = "CgkIpb2krYUDEAIQEQ"; // <GPGSID>
        public const string achievement_complete_50_classic_levels = "CgkIpb2krYUDEAIQCQ"; // <GPGSID>
        public const string achievement_collect_20_limitless_diamonds_in_one_go = "CgkIpb2krYUDEAIQCw"; // <GPGSID>
        public const string achievement_complete_30_classic_levels = "CgkIpb2krYUDEAIQBQ"; // <GPGSID>
        public const string achievement_make_150_limitless_score_in_one_go = "CgkIpb2krYUDEAIQFQ"; // <GPGSID>
        public const string achievement_collect_5_limitless_diamonds_in_one_go = "CgkIpb2krYUDEAIQCg"; // <GPGSID>
        public const string achievement_complete_20_classic_levels = "CgkIpb2krYUDEAIQBw"; // <GPGSID>
        public const string achievement_complete_5_classic_levels = "CgkIpb2krYUDEAIQAg"; // <GPGSID>
        public const string achievement_collect_50_limitless_diamonds_in_one_go = "CgkIpb2krYUDEAIQEA"; // <GPGSID>
        public const string achievement_make_50_limitless_score_in_one_go = "CgkIpb2krYUDEAIQEw"; // <GPGSID>
        public const string leaderboard_limitless_high_score = "CgkIpb2krYUDEAIQAQ"; // <GPGSID>
        public const string achievement_complete_10_classic_levels = "CgkIpb2krYUDEAIQBA"; // <GPGSID>
        public const string achievement_make_100_limitless_score_in_one_go = "CgkIpb2krYUDEAIQFA"; // <GPGSID>
        public const string achievement_collect_30_limitless_diamonds_in_one_go = "CgkIpb2krYUDEAIQDg"; // <GPGSID>

}

